# Generated by CMake 3.3.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget demo_framework scene_polyhedron_item scene_points_with_normal_item scene_implicit_function_item scene_polylines_item gl_splat)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target demo_framework
add_library(demo_framework SHARED IMPORTED)

# Create imported target scene_polyhedron_item
add_library(scene_polyhedron_item SHARED IMPORTED)

# Create imported target scene_points_with_normal_item
add_library(scene_points_with_normal_item SHARED IMPORTED)

# Create imported target scene_implicit_function_item
add_library(scene_implicit_function_item SHARED IMPORTED)

# Create imported target scene_polylines_item
add_library(scene_polylines_item SHARED IMPORTED)

# Create imported target gl_splat
add_library(gl_splat SHARED IMPORTED)

# Import target "demo_framework" for configuration "Debug"
set_property(TARGET demo_framework APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(demo_framework PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/CGAL_Project/Polyhedron/Debug/demo_framework.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Widgets;Qt5::Script;Qt5::Xml;F:/libQGLViewer-2.6.3/QGLViewer/QGLViewerd2.lib;opengl32;glu32;gl_splat"
  IMPORTED_LOCATION_DEBUG "E:/CGAL_Project/Polyhedron/Debug/demo_framework.dll"
  )

# Import target "scene_polyhedron_item" for configuration "Debug"
set_property(TARGET scene_polyhedron_item APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(scene_polyhedron_item PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/CGAL_Project/Polyhedron/Debug/scene_polyhedron_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-gd-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-gd-1_59.lib"
  IMPORTED_LOCATION_DEBUG "E:/CGAL_Project/Polyhedron/Debug/scene_polyhedron_item.dll"
  )

# Import target "scene_points_with_normal_item" for configuration "Debug"
set_property(TARGET scene_points_with_normal_item APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(scene_points_with_normal_item PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/CGAL_Project/Polyhedron/Debug/scene_points_with_normal_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-gd-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-gd-1_59.lib;gl_splat"
  IMPORTED_LOCATION_DEBUG "E:/CGAL_Project/Polyhedron/Debug/scene_points_with_normal_item.dll"
  )

# Import target "scene_implicit_function_item" for configuration "Debug"
set_property(TARGET scene_implicit_function_item APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(scene_implicit_function_item PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/CGAL_Project/Polyhedron/Debug/scene_implicit_function_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-gd-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-gd-1_59.lib"
  IMPORTED_LOCATION_DEBUG "E:/CGAL_Project/Polyhedron/Debug/scene_implicit_function_item.dll"
  )

# Import target "scene_polylines_item" for configuration "Debug"
set_property(TARGET scene_polylines_item APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(scene_polylines_item PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/CGAL_Project/Polyhedron/Debug/scene_polylines_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-gd-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-gd-1_59.lib"
  IMPORTED_LOCATION_DEBUG "E:/CGAL_Project/Polyhedron/Debug/scene_polylines_item.dll"
  )

# Import target "gl_splat" for configuration "Debug"
set_property(TARGET gl_splat APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gl_splat PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/CGAL_Project/Polyhedron/Debug/gl_splat.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml"
  IMPORTED_LOCATION_DEBUG "E:/CGAL_Project/Polyhedron/Debug/gl_splat.dll"
  )

# Import target "demo_framework" for configuration "Release"
set_property(TARGET demo_framework APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(demo_framework PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/CGAL_Project/Polyhedron/Release/demo_framework.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Widgets;Qt5::Script;Qt5::Xml;F:/libQGLViewer-2.6.3/QGLViewer/QGLViewer2.lib;opengl32;glu32;gl_splat"
  IMPORTED_LOCATION_RELEASE "E:/CGAL_Project/Polyhedron/Release/demo_framework.dll"
  )

# Import target "scene_polyhedron_item" for configuration "Release"
set_property(TARGET scene_polyhedron_item APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(scene_polyhedron_item PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/CGAL_Project/Polyhedron/Release/scene_polyhedron_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_RELEASE "E:/CGAL_Project/Polyhedron/Release/scene_polyhedron_item.dll"
  )

# Import target "scene_points_with_normal_item" for configuration "Release"
set_property(TARGET scene_points_with_normal_item APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(scene_points_with_normal_item PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/CGAL_Project/Polyhedron/Release/scene_points_with_normal_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib;gl_splat"
  IMPORTED_LOCATION_RELEASE "E:/CGAL_Project/Polyhedron/Release/scene_points_with_normal_item.dll"
  )

# Import target "scene_implicit_function_item" for configuration "Release"
set_property(TARGET scene_implicit_function_item APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(scene_implicit_function_item PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/CGAL_Project/Polyhedron/Release/scene_implicit_function_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_RELEASE "E:/CGAL_Project/Polyhedron/Release/scene_implicit_function_item.dll"
  )

# Import target "scene_polylines_item" for configuration "Release"
set_property(TARGET scene_polylines_item APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(scene_polylines_item PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/CGAL_Project/Polyhedron/Release/scene_polylines_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_RELEASE "E:/CGAL_Project/Polyhedron/Release/scene_polylines_item.dll"
  )

# Import target "gl_splat" for configuration "Release"
set_property(TARGET gl_splat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gl_splat PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/CGAL_Project/Polyhedron/Release/gl_splat.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml"
  IMPORTED_LOCATION_RELEASE "E:/CGAL_Project/Polyhedron/Release/gl_splat.dll"
  )

# Import target "demo_framework" for configuration "MinSizeRel"
set_property(TARGET demo_framework APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(demo_framework PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/demo_framework.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Widgets;Qt5::Script;Qt5::Xml;F:/libQGLViewer-2.6.3/QGLViewer/QGLViewer2.lib;opengl32;glu32;gl_splat"
  IMPORTED_LOCATION_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/demo_framework.dll"
  )

# Import target "scene_polyhedron_item" for configuration "MinSizeRel"
set_property(TARGET scene_polyhedron_item APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(scene_polyhedron_item PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/scene_polyhedron_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/scene_polyhedron_item.dll"
  )

# Import target "scene_points_with_normal_item" for configuration "MinSizeRel"
set_property(TARGET scene_points_with_normal_item APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(scene_points_with_normal_item PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/scene_points_with_normal_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib;gl_splat"
  IMPORTED_LOCATION_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/scene_points_with_normal_item.dll"
  )

# Import target "scene_implicit_function_item" for configuration "MinSizeRel"
set_property(TARGET scene_implicit_function_item APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(scene_implicit_function_item PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/scene_implicit_function_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/scene_implicit_function_item.dll"
  )

# Import target "scene_polylines_item" for configuration "MinSizeRel"
set_property(TARGET scene_polylines_item APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(scene_polylines_item PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/scene_polylines_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/scene_polylines_item.dll"
  )

# Import target "gl_splat" for configuration "MinSizeRel"
set_property(TARGET gl_splat APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(gl_splat PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/gl_splat.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml"
  IMPORTED_LOCATION_MINSIZEREL "E:/CGAL_Project/Polyhedron/MinSizeRel/gl_splat.dll"
  )

# Import target "demo_framework" for configuration "RelWithDebInfo"
set_property(TARGET demo_framework APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(demo_framework PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/demo_framework.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Widgets;Qt5::Script;Qt5::Xml;F:/libQGLViewer-2.6.3/QGLViewer/QGLViewer2.lib;opengl32;glu32;gl_splat"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/demo_framework.dll"
  )

# Import target "scene_polyhedron_item" for configuration "RelWithDebInfo"
set_property(TARGET scene_polyhedron_item APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(scene_polyhedron_item PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/scene_polyhedron_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/scene_polyhedron_item.dll"
  )

# Import target "scene_points_with_normal_item" for configuration "RelWithDebInfo"
set_property(TARGET scene_points_with_normal_item APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(scene_points_with_normal_item PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/scene_points_with_normal_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib;gl_splat"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/scene_points_with_normal_item.dll"
  )

# Import target "scene_implicit_function_item" for configuration "RelWithDebInfo"
set_property(TARGET scene_implicit_function_item APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(scene_implicit_function_item PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/scene_implicit_function_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/scene_implicit_function_item.dll"
  )

# Import target "scene_polylines_item" for configuration "RelWithDebInfo"
set_property(TARGET scene_polylines_item APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(scene_polylines_item PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/scene_polylines_item.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml;Qt5::Script;Qt5::Widgets;demo_framework;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_thread-vc120-mt-1_59.lib;C:/local/boost_1_59_0/lib64-msvc-12.0/boost_system-vc120-mt-1_59.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/scene_polylines_item.dll"
  )

# Import target "gl_splat" for configuration "RelWithDebInfo"
set_property(TARGET gl_splat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gl_splat PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/gl_splat.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "E:/CGAL-4.7/auxiliary/gmp/lib/libmpfr-4.lib;E:/CGAL-4.7/auxiliary/gmp/lib/libgmp-10.lib;glu32;opengl32;Qt5::OpenGL;Qt5::Gui;Qt5::Xml"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/CGAL_Project/Polyhedron/RelWithDebInfo/gl_splat.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
